dist: xenial
language: python
python:
        - 3.5
        - 3.6
        - 3.7
before_install:
        - pip install poetry
        - pip install mypy
install:
        - poetry install
script: mypy .

